# Generated by Django 3.0.6 on 2020-06-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='original_references',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='pdf_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='references',
            field=models.TextField(null=True),
        ),
    ]
