# Generated by Django 3.0.6 on 2020-06-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_api', '0003_auto_20200627_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='writers',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
