# Generated by Django 3.0.6 on 2020-06-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_api', '0004_auto_20200627_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
