# Generated by Django 3.0.6 on 2020-06-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_api', '0005_auto_20200627_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='pdf',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='publishing_company',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='writers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
