# Generated by Django 3.0.6 on 2020-07-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_api', '0006_auto_20200627_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.TextField(blank=True, unique=True),
        ),
    ]
